### ISSUE TITLE
Templated feature loading from feature_set.xml

### ISSUE THREAD

**Issue by rohanpaul** [tmhoward/h2sl#14]
The h2sl feature_set.xml has the following:

```
    <feature_matches_child_object invert="0"/>
    <feature_matches_child_object invert="1"/>
    <feature_matches_child_region invert="0"/>
    <feature_matches_child_region invert="1"/>
    <feature_matches_child_constraint invert="0"/>
    <feature_matches_child_constraint invert="1"/>
```

These are now templated:
feature_object_matches_child.h and .ipp
The individual feature_matches_child_region etc. have now gone away but still live in the feature_set.xml file.

How do we load in templated features from the feature_set.xml file. Do we have an example? 
Jake could you discuss this with Tom and let us know. 

Thanks

**Comment by arkinj** [comment]
The feature template 'feature_matches_child.ipp' has a constructor definition that accepts an xmlNodePtr as the function argument; this simply calls the from_xml() function.

The templated from_xml() function looks for the xml node ID by comparing against the string "feature_matches_child_ + templated class name". For example, if the feature was constructed with the Object class, the xml node should have an ID of "feature_matches_child_object", where 'object' is the output of the T::class_name() function (this is defined in the object header file). So, while the specific features are gone, the feature template looks for the same information in xml.

**Comment by rohanpaul** [comment]
Thanks Jake, this is a unique way to load the features, I had clearly overlooked this part. So, this will make the other match features easier:
feature_matches_child_
index
number
container
region_container etc.

**Comment by rohanpaul** [comment]
So derya already transferred the required match features. We can use the templated ones later and use the template ones for the new match features that we may write.

**Comment by arkinj** [comment]
We just need to be careful we are not double-dipping for certain features. Right, I think those will be handled in the same way. So, each symbol class needs to have the <class>::class_name() function defined.
