### ISSUE TITLE
'adcg' branch - Reproducing RSS Paper Results

### ISSUE THREAD

**Issue by MohitShridhar** [tmhoward/h2sl#76]
Hi There!

Can the 'adcg' branch reproduce results from your RSS paper (http://www.roboticsproceedings.org/rss12/p37.html)?

Regards

**Comment by rohanpaul** [comment]
Hi Mohit, 

Our team is working towards transferring the RSS code from our internal repository to this public repository. We are still working on cleaning up the code and data. At the moment this repo would not re-create the result. However, we are working towards releasing it along with a journal paper in the near future (may take about two months).

Thanks

**Comment by MohitShridhar** [comment]
Sounds great! Looking forward to the release!
